# Generated by Django 5.2.6 on 2025-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='תגיות מופרדות בפסיק (labels)'),
        ),
    ]
