# Generated by Django 5.2.6 on 2025-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'ללא'), ('daily', 'יומי'), ('weekly', 'שבועי'), ('monthly', 'חודשי')], default='none', help_text='חזרתיות: ללא/יומי/שבועי/חודשי', max_length=10),
        ),
    ]
